### ISSUE TITLE
Consider using mkdocs, docusaurus or gitbook to host docs

### ISSUE THREAD

**Issue by onedr0p** [petio-team/petio-docs#2]
Github wiki is great but lacks features and visibility.

There's open source alternatives (minus gitbook) that leverage Github Pages to publish docs using a Github workflow:
- https://docusaurus.io/
- mkdocs w/ https://squidfunk.github.io/mkdocs-material/ (some _unimportant_ features paid to support development)
- https://www.gitbook.com/ (free for one repository)

Using any of these, this repo can be deleted and the docs be added to the `petio-team/petio` repository and publish to github pages under https://docs.petio.tv/

**Comment by angrycuban13** [comment]
Yeah we will migrating to something else. The GH Wiki was just to get something up and running prior release. 

Thanks for the examples!

**Comment by angrycuban13** [comment]
We've opted for GitBook, thank you for the suggestion. We are still in the process of porting everything over and looking over the docs to make sure everything is updated!
