### ISSUE TITLE
Movies or Shows Coming Soon Does Not Showing Green Indictor

### ISSUE THREAD

**Issue by MMagTech** [petio-team/petio-docs#3]
Not sure if intentional or reflecting a radarr/sonarr setting. The movies or tv coming soon does not show green indictor for content already being in library. All other sections accurately reflect content in my libraries with the green indicator.

**Comment by angrycuban13** [comment]
So you opened this in the `petio-docs` repo. I think you mean to open it on https://github.com/petio-team/petio lol
